"""Полный перечень проектных инструментов и их правил исполнения."""

from src.agent.actions import ProjectAction
from src.schemas import project_tool_inputs as p
from src.services import agent_document_actions as documents
from src.services import agent_project_actions as projects
from src.services import agent_structure_actions as structure
from src.services import agent_task_actions as tasks

PROJECT_ACTIONS = (
    ProjectAction(
        "attach_uploaded_file",
        "Прикрепить файл к задаче",
        "Копирует в задачу файл, отправленный участником в личном чате. file_id берётся из uploaded_files; пути и ссылки не принимаются.",
        p.UploadedAttachmentInput,
        documents.attach_uploaded_file,
    ),
    ProjectAction(
        "get_project",
        "Прочитать проект",
        "Паспорт, статистика и история сроков текущего проекта.",
        p.EmptyInput,
        projects.get_project,
        mutating=False,
    ),
    ProjectAction(
        "update_project",
        "Обновить проект",
        "Паспорт, настройки и срок проекта; перенос срока требует причины и expected_due_date.",
        p.ProjectChangesInput,
        projects.update_project,
        owner_only=True,
    ),
    ProjectAction(
        "list_tasks",
        "Найти задачи",
        "Поиск и страница задач; возвращает ID, ключи и актуальные поля.",
        p.TaskListInput,
        tasks.list_tasks,
        mutating=False,
    ),
    ProjectAction(
        "get_task",
        "Прочитать задачу",
        "Полная задача с участниками, чек-листом, revision и updated_at.",
        p.TaskInput,
        tasks.get_task,
        mutating=False,
    ),
    ProjectAction(
        "create_task",
        "Создать задачу",
        "Создание задачи, назначений и необязательного чек-листа.",
        p.TaskCreateInput,
        tasks.create_task,
    ),
    ProjectAction(
        "update_task",
        "Изменить задачу",
        "Название, описание, приоритет, роли, участники и сроки; отсутствующие поля сохраняются, null очищает допустимое поле.",
        p.TaskUpdateInput,
        tasks.update_task,
    ),
    ProjectAction(
        "move_task",
        "Переместить задачу",
        "Стадия и положение задачи в канбане.",
        p.TaskMoveInput,
        tasks.move_task,
    ),
    ProjectAction(
        "delete_task",
        "Удалить задачу",
        "Удаляет задачу с комментариями и файлами; нужен свежий expected_updated_at и решение участника.",
        p.TaskDeleteInput,
        tasks.delete_task,
        requires_confirmation=True,
    ),
    ProjectAction(
        "set_checklist",
        "Изменить чек-лист",
        "Создать, изменить, переупорядочить, отметить пункты или удалить чек-лист; требуется его текущая revision. Сохраняй ID существующих пунктов.",
        p.ChecklistInput,
        tasks.set_checklist,
    ),
    ProjectAction(
        "fix_task_baseline",
        "Зафиксировать базовый план",
        "Записывает текущие даты задачи как baseline после решения участника.",
        p.TaskInput,
        tasks.fix_baseline,
        requires_confirmation=True,
    ),
    ProjectAction(
        "list_comments",
        "Прочитать комментарии",
        "Обсуждение задачи с ID комментариев.",
        p.TaskPageInput,
        tasks.list_comments,
        mutating=False,
    ),
    ProjectAction(
        "add_comment",
        "Добавить комментарий",
        "Комментарий от имени инициатора, определённого сервером.",
        p.CommentCreateInput,
        tasks.add_comment,
    ),
    ProjectAction(
        "update_comment",
        "Изменить комментарий",
        "Правка прочитанной версии без изменения авторства.",
        p.CommentUpdateInput,
        tasks.update_comment,
    ),
    ProjectAction(
        "delete_comment",
        "Удалить комментарий",
        "Удаляет выбранный комментарий после решения участника.",
        p.CommentInput,
        tasks.delete_comment,
        requires_confirmation=True,
    ),
    ProjectAction(
        "list_members",
        "Прочитать команду",
        "Участники, логины, ID и роли доступа; личные контакты не возвращаются.",
        p.PageInput,
        projects.list_members,
        mutating=False,
    ),
    ProjectAction(
        "add_member",
        "Добавить участника",
        "Владелец добавляет существующего пользователя по точному логину.",
        p.MemberAddInput,
        projects.add_member,
        owner_only=True,
    ),
    ProjectAction(
        "remove_member",
        "Удалить участника",
        "Владелец удаляет участника и назначения; владельца удалить нельзя.",
        p.MemberInput,
        projects.remove_member,
        requires_confirmation=True,
        owner_only=True,
    ),
    ProjectAction(
        "transfer_project_ownership",
        "Передать владение проектом",
        "Роли доступа OWNER/MEMBER: назначает нового владельца из команды, прежний становится участником.",
        p.MemberInput,
        projects.transfer_ownership,
        requires_confirmation=True,
        owner_only=True,
    ),
    ProjectAction(
        "list_stickers",
        "Прочитать стикеры",
        "Стикеры с ревизиями, координатами и привязанными задачами.",
        p.PageInput,
        projects.list_stickers,
        mutating=False,
    ),
    ProjectAction(
        "create_sticker",
        "Создать стикер",
        "Текст, цвет, положение и связи с задачами; автор задаётся сервером.",
        p.StickerCreateInput,
        projects.create_sticker,
    ),
    ProjectAction(
        "update_sticker",
        "Изменить стикер",
        "Текст, цвет и связи с задачами с проверкой revision.",
        p.StickerUpdateInput,
        projects.update_sticker,
    ),
    ProjectAction(
        "move_sticker",
        "Переместить стикер",
        "Координаты и размеры стикера.",
        p.StickerMoveInput,
        projects.move_sticker,
    ),
    ProjectAction(
        "delete_sticker",
        "Удалить стикер",
        "Удаляет прочитанную ревизию после решения участника.",
        p.StickerDeleteInput,
        projects.delete_sticker,
        requires_confirmation=True,
    ),
    ProjectAction(
        "list_documents",
        "Найти документы",
        "Постраничный перечень документов проекта.",
        p.PageInput,
        documents.list_documents,
        mutating=False,
    ),
    ProjectAction(
        "get_document",
        "Прочитать документ",
        "Страница оригинального текста и связи с задачами; next_offset указывает продолжение.",
        p.DocumentReadInput,
        documents.get_document,
        mutating=False,
    ),
    ProjectAction(
        "create_document",
        "Создать документ",
        "Документ проекта в Markdown.",
        p.DocumentCreateInput,
        documents.create_document,
    ),
    ProjectAction(
        "update_document",
        "Изменить документ",
        "Название или содержимое документа.",
        p.DocumentUpdateInput,
        documents.update_document,
    ),
    ProjectAction(
        "delete_document",
        "Удалить документ",
        "Удаляет документ и его связи после решения участника.",
        p.DocumentInput,
        documents.delete_document,
        requires_confirmation=True,
    ),
    ProjectAction(
        "link_document",
        "Прикрепить документ к задаче",
        "Связывает документ и задачу одного проекта.",
        p.DocumentLinkInput,
        documents.link_document,
    ),
    ProjectAction(
        "unlink_document",
        "Открепить документ",
        "Удаляет связь документа с задачей; сам документ сохраняется.",
        p.LinkInput,
        documents.unlink_document,
    ),
    ProjectAction(
        "list_attachments",
        "Прочитать список файлов",
        "Метаданные и ссылки файлов задачи.",
        p.TaskInput,
        documents.list_attachments,
        mutating=False,
    ),
    ProjectAction(
        "copy_attachment",
        "Прикрепить существующий файл",
        "Копирует файл одной задачи к другой внутри проекта, сохраняя исходный файл.",
        p.AttachmentCopyInput,
        documents.copy_attachment,
    ),
    ProjectAction(
        "create_text_attachment",
        "Создать текстовый файл",
        "Прикрепляет к задаче сформированный TXT, Markdown, CSV, JSON или LOG.",
        p.TextAttachmentInput,
        documents.create_text_attachment,
    ),
    ProjectAction(
        "delete_attachment",
        "Удалить файл",
        "Удаляет выбранный файл задачи после решения участника.",
        p.AttachmentInput,
        documents.delete_attachment,
        requires_confirmation=True,
    ),
    ProjectAction(
        "list_stages",
        "Прочитать стадии",
        "Стадии канбана, их ID, порядок и признак завершения.",
        p.EmptyInput,
        structure.list_stages,
        mutating=False,
    ),
    ProjectAction(
        "create_stage",
        "Создать стадию",
        "Добавляет стадию канбана.",
        p.StageCreateInput,
        structure.create_stage,
    ),
    ProjectAction(
        "update_stage",
        "Изменить стадию",
        "Название, цвет, порядок и признак завершения стадии.",
        p.StageUpdateInput,
        structure.update_stage,
    ),
    ProjectAction(
        "delete_stage",
        "Удалить стадию",
        "Удаляет стадию по правилам канбана после решения участника.",
        p.StageInput,
        structure.delete_stage,
        requires_confirmation=True,
    ),
    ProjectAction(
        "get_structure",
        "Прочитать ИСР",
        "Разделы ИСР, размещение задач и свободный пул.",
        p.EmptyInput,
        structure.get_structure,
        mutating=False,
    ),
    ProjectAction(
        "create_wbs_node",
        "Создать раздел ИСР",
        "Создаёт раздел в корне или внутри родительского раздела.",
        p.WbsCreateInput,
        structure.create_wbs_node,
    ),
    ProjectAction(
        "update_wbs_node",
        "Изменить раздел ИСР",
        "Переименовывает раздел.",
        p.WbsUpdateInput,
        structure.update_wbs_node,
    ),
    ProjectAction(
        "move_wbs_node",
        "Переместить раздел ИСР",
        "Меняет родителя и порядок с проверкой циклов.",
        p.WbsMoveInput,
        structure.move_wbs_node,
    ),
    ProjectAction(
        "delete_wbs_node",
        "Удалить раздел ИСР",
        "Удаляет раздел по правилам ИСР с сохранением задач; требует решения участника.",
        p.WbsInput,
        structure.delete_wbs_node,
        requires_confirmation=True,
    ),
    ProjectAction(
        "place_task",
        "Разместить задачу в ИСР",
        "Назначить раздел, порядок, координаты или вернуть задачу в пул через wbs_node_id=null.",
        p.TaskPlacementInput,
        structure.place_task,
    ),
    ProjectAction(
        "list_milestones",
        "Прочитать вехи",
        "Страница вех проекта с датами и статусами.",
        p.PageInput,
        structure.list_milestones,
        mutating=False,
    ),
    ProjectAction(
        "create_milestone",
        "Создать веху",
        "Новая контрольная точка проекта.",
        p.MilestoneCreateInput,
        structure.create_milestone,
    ),
    ProjectAction(
        "update_milestone",
        "Изменить веху",
        "Дата, название, статус, описание и привязка к ИСР.",
        p.MilestoneUpdateInput,
        structure.update_milestone,
    ),
    ProjectAction(
        "delete_milestone",
        "Удалить веху",
        "Удаляет веху после решения участника.",
        p.MilestoneInput,
        structure.delete_milestone,
        requires_confirmation=True,
    ),
    ProjectAction(
        "list_dependencies",
        "Прочитать зависимости",
        "Связи задач с типом и задержкой.",
        p.PageInput,
        structure.list_dependencies,
        mutating=False,
    ),
    ProjectAction(
        "create_dependency",
        "Создать зависимость",
        "Связывает задачи одного проекта с проверкой циклов.",
        p.DependencyCreateInput,
        structure.create_dependency,
    ),
    ProjectAction(
        "delete_dependency",
        "Удалить зависимость",
        "Удаляет связь задач после решения участника.",
        p.DependencyInput,
        structure.delete_dependency,
        requires_confirmation=True,
    ),
    ProjectAction(
        "get_calendar",
        "Прочитать календарь",
        "Задачи, вехи и рассчитанные сигналы в диапазоне дат.",
        p.CalendarInput,
        structure.get_calendar,
        mutating=False,
    ),
    ProjectAction(
        "preview_schedule_change",
        "Рассчитать перенос сроков",
        "Preview последствий изменения дат без записи; возвращает версии задач для apply.",
        p.ScenarioPreviewInput,
        structure.preview_schedule,
        mutating=False,
    ),
    ProjectAction(
        "apply_schedule_change",
        "Применить перенос сроков",
        "Применяет конкретные даты и expected_updated_at из preview после решения участника.",
        p.ScenarioApplyInput,
        structure.apply_schedule,
        requires_confirmation=True,
    ),
    ProjectAction(
        "list_risks",
        "Прочитать риски",
        "Фильтры и страница реестра зарегистрированных рисков проекта.",
        p.RiskListInput,
        projects.list_risks,
        mutating=False,
    ),
    ProjectAction(
        "get_risk",
        "Прочитать риск",
        "Карточка риска с оценкой, владельцем, статусом и планами.",
        p.RiskInput,
        projects.get_risk,
        mutating=False,
    ),
    ProjectAction(
        "create_risk",
        "Создать риск",
        "Добавляет риск с доменной проверкой владельца и связанной задачи.",
        p.RiskCreateInput,
        projects.create_risk,
    ),
    ProjectAction(
        "update_risk",
        "Изменить риск",
        "Поля риска, планы и статусы, включая закрытие через CLOSED.",
        p.RiskUpdateInput,
        projects.update_risk,
    ),
    ProjectAction(
        "delete_risk",
        "Удалить риск",
        "Удаляет риск после решения участника.",
        p.RiskInput,
        projects.delete_risk,
        requires_confirmation=True,
    ),
)
